"""initial schema

Revision ID: 2d2145830235
Revises:
Create Date: 2026-08-30 02:50:06.799509
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "2d2145830235"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "abuse_clusters",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("cluster_score", sa.Float(), nullable=False),
        sa.Column("account_count", sa.Integer(), nullable=False),
        sa.Column("instrument_count", sa.Integer(), nullable=False),
        sa.Column("device_count", sa.Integer(), nullable=False),
        sa.Column("ip_count", sa.Integer(), nullable=False),
        sa.Column("transaction_count", sa.Integer(), nullable=False),
        sa.Column("exposure_paise", sa.BigInteger(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("detector_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_abuse_clusters")),
        sa.UniqueConstraint("public_id", name=op.f("uq_abuse_clusters_public_id")),
    )
    op.create_table(
        "addresses",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("address_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("postal_prefix", sa.String(length=20), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_addresses")),
        sa.UniqueConstraint("address_fingerprint", name=op.f("uq_addresses_address_fingerprint")),
        sa.UniqueConstraint("public_id", name=op.f("uq_addresses_public_id")),
    )
    op.create_table(
        "audit_events",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_type", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("public_id", name=op.f("uq_audit_events_public_id")),
    )
    op.create_table(
        "customers",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.Column("account_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("customer_segment", sa.String(length=100), nullable=False),
        sa.Column("home_region", sa.String(length=100), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("public_id", name=op.f("uq_customers_public_id")),
        sa.UniqueConstraint("source_ref", name=op.f("uq_customers_source_ref")),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("generator_version", sa.String(length=100), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("transaction_count", sa.Integer(), nullable=False),
        sa.Column("legitimate_count", sa.Integer(), nullable=False),
        sa.Column("abuse_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_dataset_versions")),
    )
    op.create_table(
        "devices",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("device_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("device_type", sa.String(length=50), nullable=False),
        sa.Column("os_family", sa.String(length=50), nullable=False),
        sa.Column("browser_family", sa.String(length=50), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("device_fingerprint", name=op.f("uq_devices_device_fingerprint")),
        sa.UniqueConstraint("public_id", name=op.f("uq_devices_public_id")),
    )
    op.create_table(
        "entity_edges",
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_public_id", sa.String(length=64), nullable=False),
        sa.Column("relation_type", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_public_id", sa.String(length=64), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_edges")),
        sa.UniqueConstraint(
            "source_type",
            "source_public_id",
            "relation_type",
            "target_type",
            "target_public_id",
            name="uq_entity_edges_logical_edge",
        ),
    )
    op.create_index(
        "ix_entity_edges_source_lookup",
        "entity_edges",
        ["source_type", "source_public_id"],
        unique=False,
    )
    op.create_index(
        "ix_entity_edges_target_lookup",
        "entity_edges",
        ["target_type", "target_public_id"],
        unique=False,
    )
    op.create_table(
        "feature_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("feature_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_feature_versions")),
    )
    op.create_table(
        "investigations",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=255), nullable=False),
        sa.Column("question", sa.String(length=2000), nullable=False),
        sa.Column("evidence_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_investigations")),
        sa.UniqueConstraint("public_id", name=op.f("uq_investigations_public_id")),
    )
    op.create_table(
        "ip_addresses",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("ip_hash", sa.String(length=255), nullable=False),
        sa.Column("network_type", sa.String(length=32), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ip_addresses")),
        sa.UniqueConstraint("ip_hash", name=op.f("uq_ip_addresses_ip_hash")),
        sa.UniqueConstraint("public_id", name=op.f("uq_ip_addresses_public_id")),
    )
    op.create_table(
        "merchants",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("source_ref", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("risk_baseline", sa.Float(), nullable=False),
        sa.Column("region", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("public_id", name=op.f("uq_merchants_public_id")),
        sa.UniqueConstraint("source_ref", name=op.f("uq_merchants_source_ref")),
    )
    op.create_table(
        "payment_instruments",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("instrument_type", sa.String(length=50), nullable=False),
        sa.Column("fingerprint", sa.String(length=255), nullable=False),
        sa.Column("issuer_region", sa.String(length=100), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_instruments")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_payment_instruments_fingerprint")),
        sa.UniqueConstraint("public_id", name=op.f("uq_payment_instruments_public_id")),
    )
    op.create_table(
        "raw_events",
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processing_status", sa.String(length=32), nullable=False),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_raw_events_event_id")),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("scenario_type", sa.String(length=32), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenario_runs")),
        sa.UniqueConstraint("public_id", name=op.f("uq_scenario_runs_public_id")),
    )
    op.create_table(
        "cluster_members",
        sa.Column("cluster_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_public_id", sa.String(length=64), nullable=False),
        sa.Column("membership_score", sa.Float(), nullable=False),
        sa.Column("reason", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["abuse_clusters.id"],
            name=op.f("fk_cluster_members_cluster_id_abuse_clusters"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_members")),
    )
    op.create_index(
        "ix_cluster_members_cluster_id", "cluster_members", ["cluster_id"], unique=False
    )
    op.create_table(
        "model_versions",
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("model_type", sa.String(length=100), nullable=False),
        sa.Column("artifact_path", sa.String(length=1000), nullable=False),
        sa.Column("feature_version", sa.String(length=100), nullable=False),
        sa.Column("training_dataset_version", sa.String(length=100), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_version"],
            ["feature_versions.version"],
            name=op.f("fk_model_versions_feature_version_feature_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["training_dataset_version"],
            ["dataset_versions.version"],
            name=op.f("fk_model_versions_training_dataset_version_dataset_versions"),
        ),
        sa.PrimaryKeyConstraint("version", name=op.f("pk_model_versions")),
    )
    op.create_table(
        "transactions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("payment_instrument_id", sa.UUID(), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column("ip_address_id", sa.UUID(), nullable=False),
        sa.Column("address_id", sa.UUID(), nullable=False),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payment_method", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scenario_run_id", sa.UUID(), nullable=True),
        sa.Column("ground_truth_label", sa.String(length=32), nullable=True),
        sa.Column("ground_truth_scenario", sa.String(length=32), nullable=True),
        sa.Column("ground_truth_ring_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"], ["addresses.id"], name=op.f("fk_transactions_address_id_addresses")
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"], ["customers.id"], name=op.f("fk_transactions_customer_id_customers")
        ),
        sa.ForeignKeyConstraint(
            ["device_id"], ["devices.id"], name=op.f("fk_transactions_device_id_devices")
        ),
        sa.ForeignKeyConstraint(
            ["ip_address_id"],
            ["ip_addresses.id"],
            name=op.f("fk_transactions_ip_address_id_ip_addresses"),
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_transactions_merchant_id_merchants")
        ),
        sa.ForeignKeyConstraint(
            ["payment_instrument_id"],
            ["payment_instruments.id"],
            name=op.f("fk_transactions_payment_instrument_id_payment_instruments"),
        ),
        sa.ForeignKeyConstraint(
            ["scenario_run_id"],
            ["scenario_runs.id"],
            name=op.f("fk_transactions_scenario_run_id_scenario_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_transactions_public_id")),
    )
    op.create_index(
        "ix_transactions_address_event_time",
        "transactions",
        ["address_id", "event_time"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_customer_event_time",
        "transactions",
        ["customer_id", "event_time"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_device_event_time",
        "transactions",
        ["device_id", "event_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_event_time"), "transactions", ["event_time"], unique=False
    )
    op.create_index(
        "ix_transactions_instrument_event_time",
        "transactions",
        ["payment_instrument_id", "event_time"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_ip_event_time",
        "transactions",
        ["ip_address_id", "event_time"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_merchant_event_time",
        "transactions",
        ["merchant_id", "event_time"],
        unique=False,
    )
    op.create_table(
        "risk_predictions",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("feature_version", sa.String(length=100), nullable=False),
        sa.Column("ml_score", sa.Float(), nullable=False),
        sa.Column("graph_score", sa.Float(), nullable=False),
        sa.Column("fused_score", sa.Float(), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("top_features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("inference_latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feature_version"],
            ["feature_versions.version"],
            name=op.f("fk_risk_predictions_feature_version_feature_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.version"],
            name=op.f("fk_risk_predictions_model_version_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_risk_predictions_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_predictions")),
    )
    op.create_index(
        "ix_risk_predictions_transaction_id", "risk_predictions", ["transaction_id"], unique=False
    )
    op.create_table(
        "risk_signals",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("signal_code", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rule_version", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_risk_signals_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_signals")),
    )
    op.create_table(
        "transaction_features",
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("feature_version", sa.String(length=100), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_source_event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_version"],
            ["feature_versions.version"],
            name=op.f("fk_transaction_features_feature_version_feature_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_transaction_features_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transaction_features")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_transaction_features_transaction_id")),
    )
    op.create_table(
        "policy_decisions",
        sa.Column("public_id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.UUID(), nullable=False),
        sa.Column("risk_prediction_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("decision_reason", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["risk_prediction_id"],
            ["risk_predictions.id"],
            name=op.f("fk_policy_decisions_risk_prediction_id_risk_predictions"),
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_policy_decisions_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_decisions")),
        sa.UniqueConstraint("public_id", name=op.f("uq_policy_decisions_public_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("policy_decisions")
    op.drop_table("transaction_features")
    op.drop_table("risk_signals")
    op.drop_index("ix_risk_predictions_transaction_id", table_name="risk_predictions")
    op.drop_table("risk_predictions")
    op.drop_index("ix_transactions_merchant_event_time", table_name="transactions")
    op.drop_index("ix_transactions_ip_event_time", table_name="transactions")
    op.drop_index("ix_transactions_instrument_event_time", table_name="transactions")
    op.drop_index(op.f("ix_transactions_event_time"), table_name="transactions")
    op.drop_index("ix_transactions_device_event_time", table_name="transactions")
    op.drop_index("ix_transactions_customer_event_time", table_name="transactions")
    op.drop_index("ix_transactions_address_event_time", table_name="transactions")
    op.drop_table("transactions")
    op.drop_table("model_versions")
    op.drop_index("ix_cluster_members_cluster_id", table_name="cluster_members")
    op.drop_table("cluster_members")
    op.drop_table("scenario_runs")
    op.drop_table("raw_events")
    op.drop_table("payment_instruments")
    op.drop_table("merchants")
    op.drop_table("ip_addresses")
    op.drop_table("investigations")
    op.drop_table("feature_versions")
    op.drop_index("ix_entity_edges_target_lookup", table_name="entity_edges")
    op.drop_index("ix_entity_edges_source_lookup", table_name="entity_edges")
    op.drop_table("entity_edges")
    op.drop_table("devices")
    op.drop_table("dataset_versions")
    op.drop_table("customers")
    op.drop_table("audit_events")
    op.drop_table("addresses")
    op.drop_table("abuse_clusters")
    # ### end Alembic commands ###
